kind: pipeline
name: default
type: kubernetes

steps:
- name: build_master
  image: plugins/docker:latest
  settings:
    repo: j33r/git-mirror
    tags: latest
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKKEN
  when:
    branch:
      - master
    event:
      exclude:
        - pull_request

- name: build_dev
  image: plugins/docker:latest
  settings:
    repo: j33r/git-mirror
    tags: dev
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKEN
  when:
    branch:
      - dev
    event:
      exclude:
        - pull_request

- name: test
  image: plugins/docker:latest
  settings:
    repo: j33r/php-fpm
    tags: latest
    dockerfile: Dockerfile
    username: j33r
    password:
      from_secret: DOCKER_HUB_TOKKEN
    dry_run: true
  when:
    event:
      - pull_request
