name: 'Git Mirror'
author: jee
description: 'Mirroring current repository branch to a remote repository'
inputs:
  remote_repo:  
    description: 'remote repository url'
    required: true
  remote_repo_username:
    description: 'remote repository username'
  remote_repo_password:
    description: 'remote repository token/password'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GIT_MIRROR_REPO: ${{ inputs.remote_repo }}
    GIT_MIRROR_USER: ${{ inputs.remote_repo_username }}
    GIT_MIRROR_TOKEN: ${{ inputs.remote_repo_password }}