#!/bin/bash

# GET BRANCH NAME
echo "get proper branch name"
GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}

# CHECKOUT
echo "Checkout in commited branch"
git checkout ${GIT_BRANCH}

# ENV
echo "check if env is set"
if [ ! -z $GIT_MIRROR_USER ]; then
    echo "GIT_MIRROR_USER is set : $GIT_MIRROR_USER"
else
    echo "[ERROR] GIT_MIRROR_USER is not set"
fi

if [ ! -z $GIT_MIRROR_REPO ]; then
    echo "GIT_MIRROR_REPO is set : $GIT_MIRROR_REPO"
else
    echo "[ERROR] GIT_MIRROR_REPO is not set"
fi

if [ ! -z $GIT_MIRROR_TOKEN ]; then
    echo "GIT_MIRROR_TOKEN is set (protected): ***redacted***"
else
    echo "[ERROR] GIT_MIRROR_TOKEN is not set"
fi

# PUSH
echo "start mirroring this repo ..."
git push --force https://$GIT_MIRROR_USER:$GIT_MIRROR_TOKEN@$GIT_MIRROR_REPO $GIT_BRANCH

exit_code=$?
if [ $exit_code != 0 ]; then
    echo "[ERROR] Mirroring failed ($exit_code)"
    exit 1
else
    echo "Mirroring success"
    exit 0
fi

exit 1
