name: Mirroring to remote repos
on:
  push:
    branches:
      - master
      - dev
jobs:
  mirroring:
    name: Mirror
    run-on: ubutun-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v
      - name: mirror to gitlab.com
        uses: jee-r/docker-git-mirror@v1
        with:
          remote_repo: "gitlab.com/jee-r/docker-git-mirror.git"
          remote_repo_username: ${{ secret.GITLAB_USER }}
          remote_repo_password: ${{ secrets.GITLAB_TOKEN }}
